//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Foldit.rc
//
#define IDR_MAINFRAME                   2
#define IDR_FOLDITTYPE                  3
#define IDD_ABOUTBOX                    100
#define IDP_BUSY                        100
#define IDC_STARTFOLD                   101
#define IDD_FOLDMARKERS                 101
#define IDD_SELLANG                     101
#define IDC_AVAIL_MEM                   101
#define IDC_ENDFOLD                     102
#define IDD_EDITSTYLE                   102
#define IDD_EDITLANG                    102
#define IDC_RESOURCE_FREE               102
#define IDB_SPLASHWND                   102
#define IDC_USECOMMENTS                 103
#define IDC_STARTCOMMENT                104
#define IDC_ENDCOMMENT                  105
#define IDD_NAVIGATION                  105
#define IDC_STARTFOLDEG                 106
#define IDC_MATH_COPR                   106
#define IDC_ENDFOLDEG                   107
#define IDD_FOLDPRESENTATION            107
#define IDC_DISK_SPACE                  107
#define IDC_COMMENTS                    108
#define IDC_STANDARDFOLD                110
#define IDD_PASTELIST                   110
#define IDC_FILEFOLD                    111
#define IDD_FVIEW                       111
#define IDC_COMMENTFOLD                 112
#define IDD_SEARCH                      113
#define IDC_STATICSC                    114
#define IDC_STATICEC                    115
#define IDD_SPLASH                      115
#define IDC_STATICCF                    116
#define IDC_CURSORA                     116
#define IDC_LANGUAGELIST                117
#define IDC_CURSORB                     117
#define IDD_MISCOPTS                    118
#define IDC_LNEW                        120
#define IDC_FILTER                      121
#define IDC_LDEL                        121
#define IDC_NAME                        122
#define IDC_LEDIT                       122
#define IDC_SCOM                        123
#define IDC_LINILOAD                    123
#define IDD_TOOLBAR                     123
#define IDC_ECOM                        124
#define IDC_LINISAVE                    124
#define IDC_FREF                        125
#define IDC_TAB                         130
#define IDC_NAVFOLDOPEN                 130
#define IDC_NAVFOLDRIP                  131
#define IDC_NAVFOLDCLOSE                132
#define IDC_NAVLEFT                     135
#define IDC_NAVRIGHT                    136
#define IDC_FOLDPRESPREFIX              137
#define IDC_FOLDPRESSTARTFOLD           138
#define IDC_FOLDPRESENDFOLD             139
#define IDC_README                      143
#define IDC_COMMENT                     144
#define IDC_PASTELIST                   145
#define IDC_TEXT                        147
#define IDC_TITLE                       148
#define IDC_EDIT1                       150
#define IDC_CHECK1                      151
#define IDC_ALWAYSRIP                   151
#define IDC_DELFOLDTAILS                151
#define IDC_PASTEVIEW                   152
#define IDC_MAXIMISEVIEWS               153
#define IDC_RESTORE                     154
#define IDC_SIGNATURE                   155
#define IDC_ENDFOLDCUE                  156
#define IDC_SERIALNO                    157
#define IDC_EFOLD                       157
#define IDC_SERIALFMT                   158
#define IDC_SFOLD                       158
#define IDC_FEXT                        159
#define IDC_POPUP                       217
#define IDC_STATUSLINE                  218
#define IDC_SYSTEMFONT                  219
#define IDC_WAITTIME                    220
#define IDC_TOOLBAR                     222
#define IDW_COMBO                       223
#define IDC_SQUARE                      1000
#define IDC_ROUND                       1001
#define IDC_THREED                      1002
#define IDC_BIGICON                     1008
#define IDS_DISK_SPACE_UNAVAIL          1008
#define IDS_DISK_SPACE                  1009
#define IDC_BIGICON2                    1009
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDS_AVAIL_MEM                   1012
#define IDS_RESOURCE_FREE               1013
#define ID_OPTIONS_FOLDMARKERS          32768
#define Font                            32770
#define ID_OPTIONS_FONT                 32771
#define ID_NAVIGATE_ENTERFOLD           32772
#define ID_NAVIGATE_EXITFOLD            32773
#define ID_NAVIGATE_ENTERSELECTEDFOLD   32774
#define ID_OPTIONS_LANGUAGES            32775
#define ID_EDIT_INSERTFOLD              32776
#define ID_FOLD_CREATE                  32778
#define ID_FOLD_DELETE                  32779
#define ID_FOLD_RIP                     32780
#define ID_EDIT_DELETELINE              32782
#define ID_FOLD_UNFOLD                  32783
#define ID_OPTIONS_EDITING              32784
#define ID_TOOLS_COMMENTFOLD            32785
#define ID_OPTIONS_NAVIGATION           32786
#define ID_OPTIONS_FOLDPRESENTATION     32787
#define ID_FILE_OPENREFERENCE           32788
#define ID_EDIT_CUTLINE                 32789
#define ID_EDIT_COPYLINE                32790
#define ID_EDIT_PASTELINE               32791
#define ID_EDIT_DELETE                  32792
#define ID_DEVTEST_SHOEINTERNALPASTEBUFFER 32793
#define ID_DEBUG_DISPLAYSELECTEDTEXTPARAMETERS 32794
#define ID_TOOLS_TEXTTOFOLD             32795
#define ID_HELP_TUTORIAL                32796
#define ID_EDIT_RESTORE                 32798
#define ID_TOOLS_STARTKEYRECORDER       32801
#define ID_TOOLS_STOPKEYRECORDER        32802
#define ID_TOOLS_PLAYKEYRECORDING       32803
#define ID_BAR_FIND                     32804
#define ID_EDIT_COPYTOCLIPBOARD         32805
#define ID_EDIT_PASTEFROMCLIPBOARD      32806
#define ID_TOOLS_INSERTDATE             32807
#define ID_TOOLS_INDENTALLLINES         32808
#define ID_TOOLS_OUTDENTALLLINES        32809
#define ID_EDIT_FINDNEXT                32810
#define ID_EDIT_FINDFIRST               32811
#define ID_WINDOW_FINDSTRING            32812
#define ID_OPTIONS_MISCELLANEOUS        32813
#define ID_TOOLS_INSERTTITLE            32814
#define ID_TOOLS_INSERTFINDSTRING       32815
#define ID_TOOLS_INSERTNEXTSERIALNUMBER 32816
#define ID_TOOLS_EDITTASK               32817
#define ID_INDICATOR_LANG               59142
#define ID_INDICATOR_LINE               59143
#define ID_INDICATOR_COL                59144
#define ID_INDICATOR_RED                59145
#define ID_INDICATOR_WHO                59146
#define ID_INDICATOR_LAST               59147
#define ID_INDICATOR_DIRTY              59148
#define ID_STATIC                       -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
